language: python
python:
    - '3.5'
    - '3.6'
    - '2.7'
install:
    - pip install -r requirements.txt
    - pip install pySPM_data
before_deploy:
    - python setup.py sdist
    - python setup.py bdist_wheel
script: pytest
